// <auto-generated />
using System;
using ComicWebApp.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComicWebApp.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Number")
                        .HasColumnType("real");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("ComicChapters");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("ComicPages");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ComicSeries");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeriesAppStats", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<float>("CompletionRate")
                        .HasColumnType("real");

                    b.Property<float>("DropRate")
                        .HasColumnType("real");

                    b.Property<int>("NumberOfReaders")
                        .HasColumnType("integer");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ComicSeriesAppStats");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeriesMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .HasColumnType("text");

                    b.Property<string>("Colorist")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Genres")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Inker")
                        .HasColumnType("text");

                    b.Property<string>("OriginalLanguage")
                        .HasColumnType("text");

                    b.Property<string>("Penciler")
                        .HasColumnType("text");

                    b.Property<int>("PublicationStatus")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Themes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Writer")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ComicSeriesMetadata");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.User.ComicListEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComicSeriesId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ComicSeriesId");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ComicListEntry");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.User.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GeneralOpinion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComicWebApp.DAL.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicChapter", b =>
                {
                    b.HasOne("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeries", "Series")
                        .WithMany("Chapters")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicPage", b =>
                {
                    b.HasOne("ComicWebApp.DAL.Models.ComicSeriesModels.ComicChapter", "Chapter")
                        .WithMany("Pages")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeriesAppStats", b =>
                {
                    b.HasOne("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeries", "ComicSeries")
                        .WithOne("Stats")
                        .HasForeignKey("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeriesAppStats", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComicSeries");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeriesMetadata", b =>
                {
                    b.HasOne("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeries", "ComicSeries")
                        .WithOne("Metadata")
                        .HasForeignKey("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeriesMetadata", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComicSeries");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.User.ComicListEntry", b =>
                {
                    b.HasOne("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeries", "ComicSeries")
                        .WithMany()
                        .HasForeignKey("ComicSeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicWebApp.DAL.Models.User.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComicWebApp.DAL.Models.User.User", "User")
                        .WithMany("ComicsList")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComicSeries");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.User.User", b =>
                {
                    b.HasOne("ComicWebApp.DAL.Models.User.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("ComicWebApp.DAL.RefreshToken", b =>
                {
                    b.HasOne("ComicWebApp.DAL.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicChapter", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.ComicSeriesModels.ComicSeries", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Metadata")
                        .IsRequired();

                    b.Navigation("Stats")
                        .IsRequired();
                });

            modelBuilder.Entity("ComicWebApp.DAL.Models.User.User", b =>
                {
                    b.Navigation("ComicsList");

                    b.Navigation("Friends");
                });
#pragma warning restore 612, 618
        }
    }
}
